### ISSUE TITLE
New Composer issue Jquery 2.2.1 issue

### ISSUE THREAD

**Issue by m00nh3ck** [wbraganca/yii2-tagsinput#4]
Cannot install using composer due to composer issue.

 Problem 1
    - Conclusion: don't install wbraganca/yii2-tagsinput 1.0.1
    - Conclusion: remove bower-asset/jquery 2.2.1
    - Installation request for wbraganca/yii2-tagsinput ^1.0 -> satisfiable by wbraganca/yii2-tagsinput[1.0.0, 1.0.1].
    - Conclusion: don't install bower-asset/jquery 2.2.1
    - wbraganca/yii2-tagsinput 1.0.0 requires bower-asset/bootstrap-tagsinput ~0.5 -> satisfiable by bower-asset/bootstrap-tagsinput[0.8.0, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.0].
    - bower-asset/bootstrap-tagsinput 0.8.0 requires bower-asset/jquery ~2.1.1 -> satisfiable by bower-asset/jquery[2.1.4, 2.1.3, 2.1.2, 2.1.1].
    - bower-asset/bootstrap-tagsinput 0.7.1 requires bower-asset/jquery ~2.1.1 -> satisfiable by bower-asset/jquery[2.1.4, 2.1.3, 2.1.2, 2.1.1].
    - bower-asset/bootstrap-tagsinput 0.7.0 requires bower-asset/jquery ~2.1.1 -> satisfiable by bower-asset/jquery[2.1.4, 2.1.3, 2.1.2, 2.1.1].
    - bower-asset/bootstrap-tagsinput 0.6.1 requires bower-asset/jquery ~2.1.1 -> satisfiable by bower-asset/jquery[2.1.4, 2.1.3, 2.1.2, 2.1.1].
    - bower-asset/bootstrap-tagsinput 0.6.0 requires bower-asset/jquery ~2.1.1 -> satisfiable by bower-asset/jquery[2.1.4, 2.1.3, 2.1.2, 2.1.1].
    - bower-asset/bootstrap-tagsinput 0.5.0 requires bower-asset/jquery ~2.1.1 -> satisfiable by bower-asset/jquery[2.1.4, 2.1.3, 2.1.2, 2.1.1].
    - Can only install one of: bower-asset/jquery[2.1.4, 2.2.1].
    - Can only install one of: bower-asset/jquery[2.1.3, 2.2.1].
    - Can only install one of: bower-asset/jquery[2.1.2, 2.2.1].
    - Can only install one of: bower-asset/jquery[2.1.1, 2.2.1].
    - Installation request for bower-asset/jquery == 2.2.1.0 -> satisfiable by bower-asset/jquery[2.2.1].

**Comment by LosYear** [comment]
Same issue, but 2.2.2

**Comment by mastershaig** [comment]
same issue :-1:
