### ISSUE TITLE
New Composer issue Jquery 2.2.3 issue

### ISSUE THREAD

**Issue by greedydwarf** [wbraganca/yii2-tagsinput#6]
don't work!
please help me!
- wbraganca/yii2-tagsinput 1.0.0 requires bower-asset/bootstrap-tagsinput ~0.5 -> satisfiable by bower-asset/bootstrap-tagsinput[0.8.0, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.0].
  - wbraganca/yii2-tagsinput 1.0.1 requires bower-asset/bootstrap-tagsinput ~0.6 -> satisfiable by bower-asset/bootstrap-tagsinput[0.8.0, 0.7.1, 0.7.0, 0.6.1, 0.6.0].
  - wbraganca/yii2-tagsinput dev-master requires bower-asset/bootstrap-tagsinput ~0.6 -> satisfiable by bower-asset/bootstrap-tagsinput[0.8.0, 0.7.1, 0.7.0, 0.6.1, 0.6.0].
  - bower-asset/bootstrap-tagsinput 0.5.0 requires bower-asset/jquery ~2.1.1 -> no matching package found.
  - bower-asset/bootstrap-tagsinput 0.6.0 requires bower-asset/jquery ~2.1.1 -> no matching package found.
  - bower-asset/bootstrap-tagsinput 0.6.1 requires bower-asset/jquery ~2.1.1 -> no matching package found.
  - bower-asset/bootstrap-tagsinput 0.7.0 requires bower-asset/jquery ~2.1.1 -> no matching package found.
  - bower-asset/bootstrap-tagsinput 0.7.1 requires bower-asset/jquery ~2.1.1 -> no matching package found.
  - bower-asset/bootstrap-tagsinput 0.8.0 requires bower-asset/jquery ~2.1.1 -> no matching package found.
  - Installation request for wbraganca/yii2-tagsinput \* -> satisfiable by wbraganca/yii2-tagsinput[1.0.0, 1.0.1, dev-master].

**Comment by avikarshasaha** [comment]
i solved that issue using "bower-asset/jquery": "2.2.3 as 2.1.1" in main composer.

**Comment by kb004** [comment]
https://packagist.org/packages/life2016/yii2-tagsinput use this it has all dependencies. working fine
